set(DRONECAN_PLATFORM_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/can_driver.c
    ${CMAKE_CURRENT_LIST_DIR}/canard_stm32.c
)

set(DRONECAN_PLATFORM_HEADERS ${CMAKE_CURRENT_LIST_DIR})

if(APP_PLATFORM STREQUAL "stm32f103")
    list(APPEND DRONECAN_PLATFORM_SOURCES ${CMAKE_CURRENT_LIST_DIR}/can_rx_irq.c)
endif()
