set(DRONECAN_PLATFORM_SOURCES
)

if(APP_PLATFORM STREQUAL "stm32g0b1")
    list(APPEND DRONECAN_PLATFORM_SOURCES ${CMAKE_CURRENT_LIST_DIR}/stm32g0b1.cpp)
elseif(APP_PLATFORM STREQUAL "stm32h753xx")
    list(APPEND DRONECAN_PLATFORM_SOURCES ${CMAKE_CURRENT_LIST_DIR}/stm32h753xx.cpp)
else()
    message(FATAL_ERROR "FDCAN DroneCAN platform is unsupported for APP_PLATFORM='${APP_PLATFORM}'.")
endif()
